
// Каталог товаров, заполнение карточек
export const CATALOG = [
    {
        "id": "1",
        "title": "Foxxx Kitsune Mini Black Vintage RCA",
        "imgSrc": "card-main-1.png",
        "price": 6000,
        "like": false,
    },
    {
        "id": "2",
        "title": "Foxxx Viper Fox Golden Vintage Lot #1 RCA",
        "imgSrc": "card-main-2.png",
        "price": 8730,
        "like": false,
    },
    {
        "id": "3",
        "title": "Нитровиниловые перчатки Wally Plastic S",
        "imgSrc": "card-main-3.png",
        "price": 20,
        "like": false,
    },
    {
        "id": "4",
        "title": "Forever Cartridge Grip Ergo 30 mm Огненно-Рыжий",
        "imgSrc": "card-main-4.png",
        "price": 2037,
        "like": false,
    },
    {
        "id": "5",
        "title": "Verge Direct 2.1 Pink gip EGO 4 mm liners",
        "imgSrc": "card-main-5.png",
        "price": 2037,
        "like": false,
    },
    {
        "id": "6",
        "title": "Deuce Machines Direct Drive #7 RCA Samurai",
        "imgSrc": "card-main-6.png",
        "price": 8000,
        "like": false,
    },
    {
        "id": "7",
        "title": "Cyborg Machines Alter Rotary Axis Cross Sexy Nymph",
        "imgSrc": "card-main-7.png",
        "price": 11000,
        "like": false,
    },
    {
        "id": "8",
        "title": "Verge Direct 2.1 Gunmetal",
        "imgSrc": "card-main-8.png",
        "price": 10900,
        "like": false,
    },
    {
        "id": "9",
        "title": "Foxxx Custom NC Footswitch #2 Vintage",
        "imgSrc": "card-main-15.png",
        "price": 3500,
        "like": false,
    },
    {
        "id": "10",
        "title": "Foxxx Spark Infinity",
        "imgSrc": "card-main-14.png",
        "price": 3700,
        "like": false,
    },
    {
        "id": "11",
        "title": "Foxxx Insecticons Box V2 Domes 2 Custom",
        "imgSrc": "card-main-12.png",
        "price": 15000,
        "like": false,
    },
    {
        "id": "12",
        "title": "Foxxx Power Bank",
        "imgSrc": "card-main-13.png",
        "price": 4400,
        "like": false,
    },
    {
        "id": "13",
        "title": "Skinductor Vertigo Long Stroke",
        "imgSrc": "card-main-9.png",
        "price": 14550,
        "like": false,
    },
    {
        "id": "14",
        "title": "CNC X-WE Wireless Tattoo Pen",
        "imgSrc": "card-main-11.png",
        "price": 24444,
        "like": false,
    },
    {
        "id": "15",
        "title": "MT Vader Pen MT RCA Cord PRO 2000.135",
        "imgSrc": "card-main-10.png",
        "price": 19400,
        "like": false,
    },
]